export enum INHERITOR_CONST  {
  son = <any> "Son",
  son_of_son =  <any> "Grandson",
  father =  <any> "Father",
  daughter =  <any> "Daughter",
  father_of_father =  <any> "Paternal Grandfather ",
  brother =  <any> "Full Brother",
  nephew_paternal_halfbrother =  <any> "Nephew (paternal brother's son)",
  husband =  <any> "Husband",
  atiq =  <any> "Atiq",
  daughter_x2 =  <any> "Two Daughters",
  daughter_of_son =  <any> "Grand Daughter",
  daughter_of_son_x2 =  <any> "Two Grand Daughters",
  mother =  <any> "Mother",
  sister = <any> "Full Sister",
  paternal_halfbrother =  <any> "Paternal Brother",
  maternal_halfbrother =  <any> "Maternal Brother",
  nephew_brother =  <any> "Fraternal Nephew ",
  sister_x2 = <any> "Two Full Sisters",
  paternal_halfsister = <any> "Paternal Sister",
  paternal_halfsister_x2 = <any> "Two Paternal Sisters",
  maternal_halfsister = <any> "Maternal Sister",
  maternal_halfsister_x2 = <any> "Two Maternal Sisters",
  wife = <any> "Wife",
  mutiqa = <any> "Mutiqa",
  fathers_brother = <any>  "Uncle [father's full brother]",
  fathers_paternal_halfbrother = <any>  "Uncle (paternal brother of father)",
  grandmother_father = <any> "Grandmother (father's mother)",
  grandmother_mother = <any> "Grandmother (mother's mother)",
  son_of_fathers_brother = <any> "Cousin [son of father's full brother]",
  son_of_fathers_paternal_halfbrother = <any> "Cousin [son of father's paternal brother]"
}

export enum GENDER {
    daughter = 'daughter',   
    daughter_x2 = 'daughter_x2',
    daughter_of_son = 'daughter_of_son',
    daughter_of_son_x2 = 'daughter_of_son_x2',
    mother = 'mother',
    sister = 'sister',
    sister_x2 = 'sister_x2',
    paternal_halfsister = 'paternal_halfsister',
    paternal_halfsister_x2 = 'paternal_halfsister_x2',
    maternal_halfsister = 'maternal_halfsister',
    maternal_halfsister_x2 = 'maternal_halfsister_x2',
    wife = 'wife',
    grandmother_father = 'grandmother_father',
    grandmother_mother =' grandmother_mother' ,
  
}

export const DROPDOWN_VALUES = [
  "1/2",
 "1/3",
  "1/4",
  "1/6",
  "1/8",
  "2/3",
  "U"
]